name: DevSecOps-Pipeline

on:
    push: 
     branches: [main, feature/*]
    pull_request:
permissions:
  pull-requests: write # allows SonarQube to decorate PRs with analysis results
  contents: read
  security-events: write

jobs:
  devsecops-Build-CI:
    name: Build & Security Scans
    runs-on: self-hosted
    container:
      image: node:22-bullseye
    steps:
        - name: Checkout code
          uses: actions/checkout@v6

        # -------------------------
        # SECRETS SCANNING
        # -------------------------
        
        # - name: Secrets Scan (TruffleHog)
        #   run: |
        #     git config --global --add safe.directory "$GITHUB_WORKSPACE"
        #     curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh
        #     ./bin/trufflehog filesystem . --fail
        # -------------------------
        # SECRETS SCANNING - TRUFFLEHOG
        # -------------------------

        - name: Fix Git Safe Directory
          run: |
            git config --global --add safe.directory "$GITHUB_WORKSPACE"

        - name: TruffleHog Secret Scan (Current Branch)
          uses: trufflesecurity/trufflehog@main
          with:
            extra_args: >
              filesystem .
              --format sarif
              --no-update
              --fail

        - name: Upload TruffleHog results
          uses: github/codeql-action/upload-sarif@v3
          with:
            sarif_file: trufflehog.sarif
                
        # -------------------------
        # SAST - SonarQube
        # -------------------------

        - name: Analyze with SonarQube
          uses: SonarSource/sonarqube-scan-action@v7.0.0
          env:
           GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}  # Needed to get PR information
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on SonarQube, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}   # add the URL of your instance to the secrets of this repo with the name SONAR_HOST_URL (Settings > Secrets > Actions > add new repository secret)
          with:
           args:
            -Dsonar.projectKey=devsecops-demo
            -Dsonar.sources=.
        
        # -------------------------
        # Build
        # -------------------------
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'
            cache: 'npm'
      
        - name: Install dependencies
          run: npm ci
      
        - name: Build project
          run: npm run build
      
        - name: Upload build artifacts
          uses: actions/upload-artifact@v4
          with:
            name: build-artifacts
            path: dist/
        
  devsecops-Docker-CI:
    name: Docker & Security Scans
    runs-on: self-hosted
    needs: [devsecops-Build-CI]
    container:
      image: node:22-bullseye
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/


        
      
