name: DevSecOps-Pipeline

on:
    push: 
     branches: [main, feature/*]
    pull_request:
permissions:
  pull-requests: read # allows SonarQube to decorate PRs with analysis results


jobs:
  devsecops-CI:
    name: Build & Security Scans
    runs-on: self-hosted
    container:
      image: node:22-bullseye
    steps:
        - name: Checkout code
          uses: actions/checkout@v6
        # -------------------------
        # BUILD
        # -------------------------
        - name: Install dependencies
          run: npm ci

        - name: Build project
          run: npm run build
        
        # -------------------------
        # SAST - SonarQube
        # -------------------------
        - name: Analyze with SonarQube
          uses: SonarSource/sonarqube-scan-action@v7.0.0
          env:
           GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}  # Needed to get PR information
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on SonarQube, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}   # add the URL of your instance to the secrets of this repo with the name SONAR_HOST_URL (Settings > Secrets > Actions > add new repository secret)
          with:
           args:
            -Dsonar.projectKey=devsecops-demo
            -Dsonar.sources=.
   
        # -------------------------
        # SCA - Snyk
        # -------------------------
            
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/node@master
          continue-on-error: true
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            command: monitor
            args: --all-projects
